import type {
  BenefitPlan,
  EmployeeEnrollment,
  OpenEnrollmentPeriod,
  COBRAParticipant,
  RetirementAccount,
  BenefitsAlert,
  BenefitsSummary,
} from '@/types/benefits';

export const BENEFIT_PLANS: BenefitPlan[] = [
  {
    id: 'med-ppo-1',
    name: 'PPO Gold Plan',
    type: 'medical',
    carrier: 'Blue Cross Blue Shield',
    planCode: 'BCBS-PPO-G',
    tier: 'employee',
    employeeCost: 125,
    employerCost: 475,
    totalCost: 600,
    coverage: 'Comprehensive medical coverage with nationwide PPO network',
    deductible: 500,
    outOfPocketMax: 3000,
    coinsurance: 80,
    copay: {
      primaryCare: 25,
      specialist: 40,
      urgentCare: 50,
      emergency: 150,
      prescription: { generic: 10, brandPreferred: 35, brandNonPreferred: 60 },
    },
    features: ['Preventive care 100% covered', 'Telehealth included', 'Mental health parity', 'Maternity coverage'],
    networkType: 'PPO',
    isActive: true,
  },
  {
    id: 'med-hdhp-1',
    name: 'HDHP Bronze Plan',
    type: 'medical',
    carrier: 'Blue Cross Blue Shield',
    planCode: 'BCBS-HDHP-B',
    tier: 'employee',
    employeeCost: 65,
    employerCost: 335,
    totalCost: 400,
    coverage: 'High deductible plan with HSA eligibility',
    deductible: 1500,
    outOfPocketMax: 5000,
    coinsurance: 70,
    features: ['HSA eligible', 'Preventive care 100%', 'Lower premiums', 'Employer HSA contribution'],
    networkType: 'HDHP',
    isActive: true,
  },
  {
    id: 'dental-1',
    name: 'Dental Plus',
    type: 'dental',
    carrier: 'Delta Dental',
    planCode: 'DD-PLUS',
    tier: 'employee',
    employeeCost: 25,
    employerCost: 45,
    totalCost: 70,
    coverage: 'Comprehensive dental coverage including orthodontics',
    features: ['Preventive 100%', 'Basic 80%', 'Major 50%', 'Orthodontia 50%'],
    isActive: true,
  },
  {
    id: 'vision-1',
    name: 'Vision Care',
    type: 'vision',
    carrier: 'VSP',
    planCode: 'VSP-STD',
    tier: 'employee',
    employeeCost: 12,
    employerCost: 18,
    totalCost: 30,
    coverage: 'Annual eye exams and lens/frame allowance',
    features: ['Annual exam covered', '$150 frame allowance', 'Contact lens benefit', 'Lasik discount'],
    isActive: true,
  },
  {
    id: 'life-1',
    name: 'Basic Life & AD&D',
    type: 'life',
    carrier: 'MetLife',
    planCode: 'ML-LIFE-1X',
    tier: 'employee',
    employeeCost: 0,
    employerCost: 15,
    totalCost: 15,
    coverage: '1x annual salary up to $150,000',
    features: ['Employer paid', 'AD&D included', 'Portability option', 'Accelerated death benefit'],
    isActive: true,
  },
  {
    id: 'disability-1',
    name: 'Short-Term Disability',
    type: 'disability',
    carrier: 'MetLife',
    planCode: 'ML-STD',
    tier: 'employee',
    employeeCost: 18,
    employerCost: 0,
    totalCost: 18,
    coverage: '60% of weekly earnings up to $1,500/week',
    features: ['14-day elimination', '26-week benefit', 'Maternity coverage', 'Pre-existing waiver'],
    isActive: true,
  },
  {
    id: 'fsa-1',
    name: 'Healthcare FSA',
    type: 'fsa',
    carrier: 'HealthEquity',
    planCode: 'HE-FSA',
    tier: 'employee',
    employeeCost: 0,
    employerCost: 0,
    totalCost: 0,
    coverage: 'Pre-tax healthcare expense account up to $3,050',
    features: ['Pre-tax contributions', 'Debit card access', '$610 rollover', 'Online claims'],
    isActive: true,
  },
  {
    id: 'hsa-1',
    name: 'Health Savings Account',
    type: 'hsa',
    carrier: 'HealthEquity',
    planCode: 'HE-HSA',
    tier: 'employee',
    employeeCost: 0,
    employerCost: 50,
    totalCost: 50,
    coverage: 'Tax-advantaged savings for qualified medical expenses',
    features: ['Triple tax advantage', 'Investment options', 'Employer contribution', 'Portable'],
    isActive: true,
  },
  {
    id: '401k-1',
    name: '401(k) Retirement Plan',
    type: '401k',
    carrier: 'Fidelity',
    planCode: 'FID-401K',
    tier: 'employee',
    employeeCost: 0,
    employerCost: 0,
    totalCost: 0,
    coverage: 'Tax-deferred retirement savings with employer match',
    features: ['4% employer match', 'Immediate vesting', 'Roth option', 'Loan available'],
    isActive: true,
  },
];

export const EMPLOYEE_ENROLLMENTS: EmployeeEnrollment[] = [
  {
    id: 'enr-001',
    employeeId: 'emp-001',
    employeeName: 'Maria Garcia',
    department: 'Production',
    enrollmentDate: '2024-11-01',
    effectiveDate: '2025-01-01',
    status: 'active',
    plans: [
      { planId: 'med-ppo-1', planName: 'PPO Gold Plan', planType: 'medical', tier: 'family', employeeCost: 425, dependents: ['Carlos Garcia', 'Sofia Garcia'] },
      { planId: 'dental-1', planName: 'Dental Plus', planType: 'dental', tier: 'family', employeeCost: 75, dependents: ['Carlos Garcia', 'Sofia Garcia'] },
      { planId: 'vision-1', planName: 'Vision Care', planType: 'vision', tier: 'family', employeeCost: 28, dependents: ['Carlos Garcia', 'Sofia Garcia'] },
      { planId: '401k-1', planName: '401(k) Plan', planType: '401k', tier: 'employee', employeeCost: 0, dependents: [] },
    ],
    totalMonthlyDeduction: 528,
    annualElection: 6336,
    lifeEvents: [
      { date: '2024-06-15', type: 'Marriage', description: 'Added spouse Carlos Garcia to benefits' },
    ],
  },
  {
    id: 'enr-002',
    employeeId: 'emp-002',
    employeeName: 'James Wilson',
    department: 'Maintenance',
    enrollmentDate: '2024-11-05',
    effectiveDate: '2025-01-01',
    status: 'active',
    plans: [
      { planId: 'med-hdhp-1', planName: 'HDHP Bronze Plan', planType: 'medical', tier: 'employee', employeeCost: 65, dependents: [] },
      { planId: 'hsa-1', planName: 'Health Savings Account', planType: 'hsa', tier: 'employee', employeeCost: 200, dependents: [] },
      { planId: 'life-1', planName: 'Basic Life & AD&D', planType: 'life', tier: 'employee', employeeCost: 0, dependents: [] },
    ],
    totalMonthlyDeduction: 265,
    annualElection: 3180,
    lifeEvents: [],
  },
  {
    id: 'enr-003',
    employeeId: 'emp-003',
    employeeName: 'Sarah Johnson',
    department: 'Quality',
    enrollmentDate: '2024-11-03',
    effectiveDate: '2025-01-01',
    status: 'pending',
    plans: [
      { planId: 'med-ppo-1', planName: 'PPO Gold Plan', planType: 'medical', tier: 'employee_spouse', employeeCost: 275, dependents: ['Michael Johnson'] },
      { planId: 'dental-1', planName: 'Dental Plus', planType: 'dental', tier: 'employee_spouse', employeeCost: 50, dependents: ['Michael Johnson'] },
    ],
    totalMonthlyDeduction: 325,
    annualElection: 3900,
    lifeEvents: [],
  },
  {
    id: 'enr-004',
    employeeId: 'emp-004',
    employeeName: 'Robert Chen',
    department: 'Warehouse',
    enrollmentDate: '2024-11-01',
    effectiveDate: '2025-01-01',
    status: 'waived',
    plans: [],
    totalMonthlyDeduction: 0,
    annualElection: 0,
    lifeEvents: [
      { date: '2024-11-01', type: 'Coverage Waiver', description: 'Covered under spouse employer plan' },
    ],
  },
  {
    id: 'enr-005',
    employeeId: 'emp-005',
    employeeName: 'Emily Davis',
    department: 'Administration',
    enrollmentDate: '2024-11-02',
    effectiveDate: '2025-01-01',
    status: 'active',
    plans: [
      { planId: 'med-ppo-1', planName: 'PPO Gold Plan', planType: 'medical', tier: 'employee_children', employeeCost: 325, dependents: ['Emma Davis', 'Ethan Davis'] },
      { planId: 'dental-1', planName: 'Dental Plus', planType: 'dental', tier: 'employee_children', employeeCost: 62, dependents: ['Emma Davis', 'Ethan Davis'] },
      { planId: 'vision-1', planName: 'Vision Care', planType: 'vision', tier: 'employee_children', employeeCost: 24, dependents: ['Emma Davis', 'Ethan Davis'] },
      { planId: 'fsa-1', planName: 'Healthcare FSA', planType: 'fsa', tier: 'employee', employeeCost: 125, dependents: [] },
      { planId: '401k-1', planName: '401(k) Plan', planType: '401k', tier: 'employee', employeeCost: 0, dependents: [] },
    ],
    totalMonthlyDeduction: 536,
    annualElection: 6432,
    lifeEvents: [
      { date: '2024-03-20', type: 'Birth', description: 'Added newborn Ethan Davis to benefits' },
    ],
  },
];

export const OPEN_ENROLLMENT_PERIODS: OpenEnrollmentPeriod[] = [
  {
    id: 'oe-2025',
    year: 2025,
    name: '2025 Open Enrollment',
    startDate: '2024-11-01',
    endDate: '2024-11-30',
    effectiveDate: '2025-01-01',
    status: 'active',
    eligibleEmployees: 156,
    enrolled: 98,
    pending: 42,
    waived: 16,
    changesAllowed: true,
    remindersSent: 3,
  },
  {
    id: 'oe-2024',
    year: 2024,
    name: '2024 Open Enrollment',
    startDate: '2023-11-01',
    endDate: '2023-11-30',
    effectiveDate: '2024-01-01',
    status: 'completed',
    eligibleEmployees: 148,
    enrolled: 132,
    pending: 0,
    waived: 16,
    changesAllowed: false,
    remindersSent: 4,
  },
];

export const COBRA_PARTICIPANTS: COBRAParticipant[] = [
  {
    id: 'cobra-001',
    formerEmployeeId: 'emp-former-001',
    formerEmployeeName: 'Thomas Anderson',
    qualifyingEvent: 'termination',
    qualifyingEventDate: '2024-09-15',
    notificationDate: '2024-09-18',
    electionDeadline: '2024-11-17',
    electedDate: '2024-10-01',
    status: 'elected',
    coveredPlans: ['med-ppo-1', 'dental-1'],
    monthlyPremium: 650,
    totalMonthlyPremium: 650,
    remainingMonths: 14,
    electedPlans: [
      { planId: 'med-ppo-1', planName: 'PPO Gold Plan', planType: 'medical', monthlyPremium: 600 },
      { planId: 'dental-1', planName: 'Dental Plus', planType: 'dental', monthlyPremium: 50 },
    ],
    coveredDependents: ['Lisa Anderson'],
    paidThrough: '2024-12-31',
  },
  {
    id: 'cobra-002',
    formerEmployeeId: 'emp-former-002',
    formerEmployeeName: 'Jennifer Martinez',
    qualifyingEvent: 'reduction_hours',
    qualifyingEventDate: '2024-10-01',
    notificationDate: '2024-10-05',
    electionDeadline: '2024-12-05',
    status: 'pending_election',
    coveredPlans: ['med-hdhp-1'],
    monthlyPremium: 400,
    totalMonthlyPremium: 400,
    remainingMonths: 18,
    electedPlans: [],
    coveredDependents: [],
  },
  {
    id: 'cobra-003',
    formerEmployeeId: 'emp-former-003',
    formerEmployeeName: 'David Kim',
    qualifyingEvent: 'termination',
    qualifyingEventDate: '2024-08-01',
    notificationDate: '2024-08-05',
    electionDeadline: '2024-10-05',
    status: 'declined',
    coveredPlans: [],
    monthlyPremium: 0,
    totalMonthlyPremium: 0,
    remainingMonths: 0,
    electedPlans: [],
    coveredDependents: [],
  },
];

export const RETIREMENT_ACCOUNTS: RetirementAccount[] = [
  {
    id: 'ret-001',
    employeeId: 'emp-001',
    employeeName: 'Maria Garcia',
    department: 'Production',
    accountType: '401k',
    totalBalance: 87500,
    contributionPercent: 8,
    vestedPercent: 100,
    ytdContributions: 6800,
    ytdEmployerMatch: 3400,
    isAutoEscalate: true,
    loans: [],
  },
  {
    id: 'ret-002',
    employeeId: 'emp-002',
    employeeName: 'James Wilson',
    department: 'Maintenance',
    accountType: '401k',
    totalBalance: 45200,
    contributionPercent: 6,
    vestedPercent: 75,
    ytdContributions: 4200,
    ytdEmployerMatch: 2800,
    isAutoEscalate: false,
    loans: [
      {
        id: 'loan-001',
        originalAmount: 10000,
        remainingBalance: 7500,
        monthlyPayment: 215,
        startDate: '2024-03-01',
        endDate: '2028-02-28',
      },
    ],
  },
  {
    id: 'ret-003',
    employeeId: 'emp-005',
    employeeName: 'Emily Davis',
    department: 'Administration',
    accountType: '401k_roth',
    totalBalance: 62800,
    contributionPercent: 10,
    vestedPercent: 100,
    ytdContributions: 8500,
    ytdEmployerMatch: 3400,
    isAutoEscalate: true,
    loans: [],
  },
];

export const BENEFITS_ALERTS: BenefitsAlert[] = [
  {
    id: 'alert-001',
    type: 'enrollment',
    priority: 'high',
    title: 'Open Enrollment Deadline Approaching',
    message: '42 employees have not completed their benefit elections. Deadline is November 30th.',
    date: '2024-11-15',
    isRead: false,
    actionRequired: true,
  },
  {
    id: 'alert-002',
    type: 'cobra',
    priority: 'high',
    title: 'COBRA Election Deadline',
    message: 'Jennifer Martinez COBRA election deadline is December 5th. Send reminder notification.',
    date: '2024-11-14',
    isRead: false,
    actionRequired: true,
  },
  {
    id: 'alert-003',
    type: '401k',
    priority: 'medium',
    title: 'Quarterly Contribution Limit Check',
    message: '3 employees are on track to exceed IRS contribution limits. Review and adjust.',
    date: '2024-11-10',
    isRead: true,
    actionRequired: false,
  },
  {
    id: 'alert-004',
    type: 'compliance',
    priority: 'medium',
    title: 'ACA Reporting Reminder',
    message: 'Form 1095-C preparation should begin. Deadline is January 31st.',
    date: '2024-11-08',
    isRead: true,
    actionRequired: false,
  },
  {
    id: 'alert-005',
    type: 'payment',
    priority: 'low',
    title: 'Premium Invoice Received',
    message: 'December medical premium invoice received from BCBS. Amount: $74,250.',
    date: '2024-11-05',
    isRead: true,
    actionRequired: false,
  },
];

export const BENEFITS_SUMMARY: BenefitsSummary = {
  totalEligible: 156,
  totalEnrolled: 140,
  totalWaived: 16,
  participationRate: 90,
  totalMonthlyPremiums: 74250,
  employerContribution: 52000,
  cobraParticipants: 2,
  totalRetirementAssets: 2450000,
  averageContributionRate: 7.2,
};
