-- Ergonomics & Industrial Hygiene Tables

-- Ergonomic Assessments
CREATE TABLE ergonomic_assessments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  assessment_number TEXT NOT NULL,
  employee_id UUID REFERENCES employees(id),
  employee_name TEXT NOT NULL,
  employee_department TEXT,
  employee_job_title TEXT,
  facility_id UUID REFERENCES facilities(id),
  facility_name TEXT,
  assessment_date DATE NOT NULL,
  assessment_type TEXT NOT NULL CHECK (assessment_type IN ('initial', 'follow_up', 'complaint', 'periodic', 'post_injury')),
  work_area TEXT NOT NULL,
  job_tasks TEXT[],
  hours_per_day DECIMAL(4,2),
  days_per_week INTEGER,
  physical_demands JSONB DEFAULT '{}',
  posture_assessment JSONB DEFAULT '{}',
  workstation_setup JSONB DEFAULT '{}',
  tools_equipment TEXT[],
  environmental_factors JSONB DEFAULT '{}',
  risk_factors_identified TEXT[],
  overall_risk_level TEXT NOT NULL CHECK (overall_risk_level IN ('low', 'moderate', 'high', 'very_high')),
  recommendations TEXT[],
  priority_actions TEXT[],
  employee_concerns TEXT,
  employee_symptoms TEXT[],
  symptom_duration TEXT,
  symptom_frequency TEXT,
  previous_injuries TEXT,
  accommodations_needed TEXT[],
  follow_up_required BOOLEAN DEFAULT FALSE,
  follow_up_date DATE,
  assessor_id UUID REFERENCES employees(id),
  assessor_name TEXT NOT NULL,
  assessor_title TEXT,
  reviewed_by TEXT,
  reviewed_by_id UUID REFERENCES employees(id),
  reviewed_date DATE,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'completed', 'pending_review', 'action_required', 'closed')),
  attachments JSONB DEFAULT '[]',
  photos JSONB DEFAULT '[]',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(organization_id, assessment_number)
);

-- Workstation Evaluations
CREATE TABLE workstation_evaluations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  evaluation_number TEXT NOT NULL,
  employee_id UUID REFERENCES employees(id),
  employee_name TEXT NOT NULL,
  employee_department TEXT,
  facility_id UUID REFERENCES facilities(id),
  facility_name TEXT,
  location TEXT NOT NULL,
  workstation_type TEXT NOT NULL CHECK (workstation_type IN ('office', 'industrial', 'laboratory', 'assembly', 'computer', 'standing', 'sit_stand', 'vehicle', 'other')),
  evaluation_date DATE NOT NULL,
  evaluator_id UUID REFERENCES employees(id),
  evaluator_name TEXT NOT NULL,
  chair_assessment JSONB DEFAULT '{}',
  desk_assessment JSONB DEFAULT '{}',
  monitor_assessment JSONB DEFAULT '{}',
  keyboard_mouse_assessment JSONB DEFAULT '{}',
  lighting_assessment JSONB DEFAULT '{}',
  noise_level_db DECIMAL(5,2),
  temperature_f DECIMAL(5,2),
  humidity_percent DECIMAL(5,2),
  ventilation_adequate BOOLEAN,
  floor_condition TEXT,
  mat_required BOOLEAN,
  anti_fatigue_mat_present BOOLEAN,
  footrest_required BOOLEAN,
  footrest_present BOOLEAN,
  document_holder_required BOOLEAN,
  document_holder_present BOOLEAN,
  phone_headset_required BOOLEAN,
  phone_headset_present BOOLEAN,
  overall_score INTEGER CHECK (overall_score >= 0 AND overall_score <= 100),
  compliance_status TEXT DEFAULT 'compliant' CHECK (compliance_status IN ('compliant', 'non_compliant', 'needs_improvement')),
  issues_identified TEXT[],
  recommendations TEXT[],
  equipment_needed TEXT[],
  estimated_cost DECIMAL(10,2),
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  action_items JSONB DEFAULT '[]',
  follow_up_required BOOLEAN DEFAULT FALSE,
  follow_up_date DATE,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'closed')),
  employee_signature TEXT,
  employee_signed_date DATE,
  supervisor_signature TEXT,
  supervisor_signed_date DATE,
  attachments JSONB DEFAULT '[]',
  photos JSONB DEFAULT '[]',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(organization_id, evaluation_number)
);

-- Noise Monitoring Records
CREATE TABLE noise_monitoring (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  monitoring_number TEXT NOT NULL,
  facility_id UUID REFERENCES facilities(id),
  facility_name TEXT,
  location TEXT NOT NULL,
  area_description TEXT,
  monitoring_date DATE NOT NULL,
  monitoring_type TEXT NOT NULL CHECK (monitoring_type IN ('area', 'personal', 'task_based', 'baseline', 'follow_up')),
  equipment_used TEXT NOT NULL,
  equipment_serial TEXT,
  calibration_date DATE,
  calibration_due DATE,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  duration_minutes INTEGER,
  employee_id UUID REFERENCES employees(id),
  employee_name TEXT,
  job_title TEXT,
  tasks_monitored TEXT[],
  twa_db DECIMAL(5,2) NOT NULL,
  max_db DECIMAL(5,2),
  min_db DECIMAL(5,2),
  peak_db DECIMAL(5,2),
  dose_percent DECIMAL(6,2),
  exchange_rate INTEGER DEFAULT 5,
  criterion_level INTEGER DEFAULT 90,
  threshold_level INTEGER DEFAULT 80,
  action_level INTEGER DEFAULT 85,
  exceeds_action_level BOOLEAN DEFAULT FALSE,
  exceeds_pel BOOLEAN DEFAULT FALSE,
  hearing_protection_required BOOLEAN DEFAULT FALSE,
  current_hearing_protection TEXT,
  recommended_hearing_protection TEXT,
  nrr_required INTEGER,
  engineering_controls_present TEXT[],
  engineering_controls_recommended TEXT[],
  administrative_controls_present TEXT[],
  administrative_controls_recommended TEXT[],
  noise_sources TEXT[],
  weather_conditions TEXT,
  background_noise_db DECIMAL(5,2),
  monitored_by TEXT NOT NULL,
  monitored_by_id UUID REFERENCES employees(id),
  reviewed_by TEXT,
  reviewed_by_id UUID REFERENCES employees(id),
  reviewed_date DATE,
  status TEXT DEFAULT 'completed' CHECK (status IN ('scheduled', 'in_progress', 'completed', 'cancelled')),
  compliance_status TEXT DEFAULT 'compliant' CHECK (compliance_status IN ('compliant', 'non_compliant', 'action_required')),
  corrective_actions TEXT[],
  follow_up_required BOOLEAN DEFAULT FALSE,
  follow_up_date DATE,
  attachments JSONB DEFAULT '[]',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(organization_id, monitoring_number)
);

-- Heat Stress Monitoring
CREATE TABLE heat_stress_monitoring (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  monitoring_number TEXT NOT NULL,
  facility_id UUID REFERENCES facilities(id),
  facility_name TEXT,
  location TEXT NOT NULL,
  work_area TEXT,
  monitoring_date DATE NOT NULL,
  monitoring_time TIME NOT NULL,
  monitoring_type TEXT NOT NULL CHECK (monitoring_type IN ('routine', 'hot_weather', 'incident_response', 'baseline', 'follow_up')),
  dry_bulb_temp_f DECIMAL(5,2),
  wet_bulb_temp_f DECIMAL(5,2),
  globe_temp_f DECIMAL(5,2),
  wbgt_index DECIMAL(5,2),
  relative_humidity DECIMAL(5,2),
  air_velocity_fpm DECIMAL(6,2),
  radiant_heat_source TEXT,
  clothing_adjustment DECIMAL(3,1) DEFAULT 0,
  metabolic_rate TEXT CHECK (metabolic_rate IN ('light', 'moderate', 'heavy', 'very_heavy')),
  work_rest_regime TEXT,
  recommended_work_rest TEXT,
  employee_id UUID REFERENCES employees(id),
  employee_name TEXT,
  job_task TEXT,
  exposure_duration_minutes INTEGER,
  hydration_available BOOLEAN DEFAULT TRUE,
  hydration_frequency TEXT,
  shade_available BOOLEAN,
  cooling_available BOOLEAN,
  cooling_type TEXT,
  ppe_worn TEXT[],
  acclimatization_status TEXT CHECK (acclimatization_status IN ('acclimatized', 'not_acclimatized', 'partial')),
  heat_index TEXT CHECK (heat_index IN ('caution', 'extreme_caution', 'danger', 'extreme_danger', 'safe')),
  action_limit_exceeded BOOLEAN DEFAULT FALSE,
  threshold_limit_exceeded BOOLEAN DEFAULT FALSE,
  symptoms_reported TEXT[],
  first_aid_provided BOOLEAN DEFAULT FALSE,
  first_aid_details TEXT,
  engineering_controls TEXT[],
  administrative_controls TEXT[],
  recommended_controls TEXT[],
  monitored_by TEXT NOT NULL,
  monitored_by_id UUID REFERENCES employees(id),
  reviewed_by TEXT,
  reviewed_by_id UUID REFERENCES employees(id),
  reviewed_date DATE,
  status TEXT DEFAULT 'completed' CHECK (status IN ('scheduled', 'in_progress', 'completed', 'cancelled')),
  follow_up_required BOOLEAN DEFAULT FALSE,
  follow_up_date DATE,
  attachments JSONB DEFAULT '[]',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(organization_id, monitoring_number)
);

-- Air Quality Monitoring
CREATE TABLE air_quality_monitoring (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  monitoring_number TEXT NOT NULL,
  facility_id UUID REFERENCES facilities(id),
  facility_name TEXT,
  location TEXT NOT NULL,
  area_description TEXT,
  monitoring_date DATE NOT NULL,
  monitoring_type TEXT NOT NULL CHECK (monitoring_type IN ('routine', 'complaint', 'incident', 'baseline', 'follow_up', 'exposure_assessment')),
  sample_type TEXT NOT NULL CHECK (sample_type IN ('area', 'personal', 'grab', 'continuous')),
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  duration_minutes INTEGER,
  employee_id UUID REFERENCES employees(id),
  employee_name TEXT,
  job_task TEXT,
  contaminant_type TEXT NOT NULL CHECK (contaminant_type IN ('particulate', 'gas', 'vapor', 'fume', 'mist', 'dust', 'biological', 'multiple')),
  contaminant_name TEXT NOT NULL,
  cas_number TEXT,
  sampling_method TEXT NOT NULL,
  equipment_used TEXT NOT NULL,
  equipment_serial TEXT,
  calibration_date DATE,
  flow_rate_lpm DECIMAL(6,3),
  sample_volume_liters DECIMAL(8,2),
  lab_sample_id TEXT,
  lab_name TEXT,
  analysis_method TEXT,
  result_value DECIMAL(12,6),
  result_unit TEXT NOT NULL,
  detection_limit DECIMAL(12,6),
  osha_pel DECIMAL(12,6),
  osha_pel_unit TEXT,
  acgih_tlv DECIMAL(12,6),
  acgih_tlv_unit TEXT,
  niosh_rel DECIMAL(12,6),
  niosh_rel_unit TEXT,
  stel_value DECIMAL(12,6),
  ceiling_value DECIMAL(12,6),
  percent_of_pel DECIMAL(6,2),
  exceeds_action_level BOOLEAN DEFAULT FALSE,
  exceeds_pel BOOLEAN DEFAULT FALSE,
  exceeds_stel BOOLEAN DEFAULT FALSE,
  respiratory_protection_required BOOLEAN DEFAULT FALSE,
  current_respirator TEXT,
  recommended_respirator TEXT,
  ventilation_type TEXT,
  ventilation_adequate BOOLEAN,
  engineering_controls TEXT[],
  administrative_controls TEXT[],
  recommended_controls TEXT[],
  weather_conditions TEXT,
  temperature_f DECIMAL(5,2),
  humidity_percent DECIMAL(5,2),
  barometric_pressure DECIMAL(6,2),
  sampled_by TEXT NOT NULL,
  sampled_by_id UUID REFERENCES employees(id),
  reviewed_by TEXT,
  reviewed_by_id UUID REFERENCES employees(id),
  reviewed_date DATE,
  status TEXT DEFAULT 'pending_results' CHECK (status IN ('scheduled', 'in_progress', 'pending_results', 'completed', 'cancelled')),
  compliance_status TEXT CHECK (compliance_status IN ('compliant', 'non_compliant', 'action_required')),
  corrective_actions TEXT[],
  follow_up_required BOOLEAN DEFAULT FALSE,
  follow_up_date DATE,
  attachments JSONB DEFAULT '[]',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(organization_id, monitoring_number)
);

-- Repetitive Motion Risk Assessments
CREATE TABLE repetitive_motion_assessments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  assessment_number TEXT NOT NULL,
  employee_id UUID REFERENCES employees(id),
  employee_name TEXT NOT NULL,
  employee_department TEXT,
  employee_job_title TEXT,
  facility_id UUID REFERENCES facilities(id),
  facility_name TEXT,
  work_area TEXT NOT NULL,
  job_task TEXT NOT NULL,
  assessment_date DATE NOT NULL,
  assessment_type TEXT NOT NULL CHECK (assessment_type IN ('initial', 'follow_up', 'complaint', 'periodic', 'post_injury')),
  assessor_id UUID REFERENCES employees(id),
  assessor_name TEXT NOT NULL,
  task_duration_hours DECIMAL(4,2),
  cycle_time_seconds INTEGER,
  cycles_per_shift INTEGER,
  force_level TEXT CHECK (force_level IN ('light', 'moderate', 'heavy', 'very_heavy')),
  force_description TEXT,
  repetition_rate TEXT CHECK (repetition_rate IN ('low', 'moderate', 'high', 'very_high')),
  awkward_postures JSONB DEFAULT '{}',
  contact_stress JSONB DEFAULT '{}',
  vibration_exposure JSONB DEFAULT '{}',
  static_postures JSONB DEFAULT '{}',
  body_parts_affected TEXT[],
  strain_index_score DECIMAL(6,2),
  rula_score INTEGER CHECK (rula_score >= 1 AND rula_score <= 7),
  reba_score INTEGER CHECK (reba_score >= 1 AND reba_score <= 15),
  ocra_index DECIMAL(6,2),
  hal_tlv_score DECIMAL(4,2),
  overall_risk_level TEXT NOT NULL CHECK (overall_risk_level IN ('low', 'moderate', 'high', 'very_high')),
  current_controls TEXT[],
  recommended_engineering_controls TEXT[],
  recommended_administrative_controls TEXT[],
  recommended_ppe TEXT[],
  tool_modifications TEXT[],
  workstation_modifications TEXT[],
  work_practice_changes TEXT[],
  job_rotation_recommended BOOLEAN DEFAULT FALSE,
  rotation_schedule TEXT,
  rest_breaks_recommended TEXT,
  stretching_program BOOLEAN DEFAULT FALSE,
  employee_symptoms TEXT[],
  symptom_body_parts TEXT[],
  symptom_duration TEXT,
  symptom_frequency TEXT,
  previous_msd_history TEXT,
  medical_restrictions TEXT,
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  implementation_timeline TEXT,
  estimated_cost DECIMAL(10,2),
  follow_up_required BOOLEAN DEFAULT FALSE,
  follow_up_date DATE,
  reviewed_by TEXT,
  reviewed_by_id UUID REFERENCES employees(id),
  reviewed_date DATE,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'completed', 'pending_review', 'action_required', 'closed')),
  attachments JSONB DEFAULT '[]',
  photos JSONB DEFAULT '[]',
  videos JSONB DEFAULT '[]',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(organization_id, assessment_number)
);

-- Enable RLS
ALTER TABLE ergonomic_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE workstation_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE noise_monitoring ENABLE ROW LEVEL SECURITY;
ALTER TABLE heat_stress_monitoring ENABLE ROW LEVEL SECURITY;
ALTER TABLE air_quality_monitoring ENABLE ROW LEVEL SECURITY;
ALTER TABLE repetitive_motion_assessments ENABLE ROW LEVEL SECURITY;

-- Create indexes
CREATE INDEX idx_ergonomic_assessments_org ON ergonomic_assessments(organization_id);
CREATE INDEX idx_ergonomic_assessments_employee ON ergonomic_assessments(organization_id, employee_id);
CREATE INDEX idx_ergonomic_assessments_date ON ergonomic_assessments(organization_id, assessment_date);
CREATE INDEX idx_ergonomic_assessments_status ON ergonomic_assessments(organization_id, status);

CREATE INDEX idx_workstation_evaluations_org ON workstation_evaluations(organization_id);
CREATE INDEX idx_workstation_evaluations_employee ON workstation_evaluations(organization_id, employee_id);
CREATE INDEX idx_workstation_evaluations_date ON workstation_evaluations(organization_id, evaluation_date);
CREATE INDEX idx_workstation_evaluations_status ON workstation_evaluations(organization_id, status);

CREATE INDEX idx_noise_monitoring_org ON noise_monitoring(organization_id);
CREATE INDEX idx_noise_monitoring_facility ON noise_monitoring(organization_id, facility_id);
CREATE INDEX idx_noise_monitoring_date ON noise_monitoring(organization_id, monitoring_date);
CREATE INDEX idx_noise_monitoring_status ON noise_monitoring(organization_id, status);

CREATE INDEX idx_heat_stress_monitoring_org ON heat_stress_monitoring(organization_id);
CREATE INDEX idx_heat_stress_monitoring_facility ON heat_stress_monitoring(organization_id, facility_id);
CREATE INDEX idx_heat_stress_monitoring_date ON heat_stress_monitoring(organization_id, monitoring_date);

CREATE INDEX idx_air_quality_monitoring_org ON air_quality_monitoring(organization_id);
CREATE INDEX idx_air_quality_monitoring_facility ON air_quality_monitoring(organization_id, facility_id);
CREATE INDEX idx_air_quality_monitoring_date ON air_quality_monitoring(organization_id, monitoring_date);
CREATE INDEX idx_air_quality_monitoring_status ON air_quality_monitoring(organization_id, status);

CREATE INDEX idx_repetitive_motion_org ON repetitive_motion_assessments(organization_id);
CREATE INDEX idx_repetitive_motion_employee ON repetitive_motion_assessments(organization_id, employee_id);
CREATE INDEX idx_repetitive_motion_date ON repetitive_motion_assessments(organization_id, assessment_date);
CREATE INDEX idx_repetitive_motion_status ON repetitive_motion_assessments(organization_id, status);

-- Add triggers for updated_at
CREATE TRIGGER update_ergonomic_assessments_updated_at BEFORE UPDATE ON ergonomic_assessments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_workstation_evaluations_updated_at BEFORE UPDATE ON workstation_evaluations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_noise_monitoring_updated_at BEFORE UPDATE ON noise_monitoring FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_heat_stress_monitoring_updated_at BEFORE UPDATE ON heat_stress_monitoring FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_air_quality_monitoring_updated_at BEFORE UPDATE ON air_quality_monitoring FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_repetitive_motion_assessments_updated_at BEFORE UPDATE ON repetitive_motion_assessments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
